apiVersion: v1
kind: ServiceAccount
metadata:
  name: model-token-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: model-token-service-account-access
rules:
- apiGroups: ["serving.kserve.io"]
  resources: ["inferenceservices"]
  verbs: ["get", "list", "watch", "view"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: model-token-service-account-bind
subjects:
- kind: ServiceAccount
  name: model-token-service-account
roleRef:
  kind: Role
  name: model-token-service-account-access
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: model-token-service-account-token
  annotations:
    kubernetes.io/service-account.name: model-token-service-account
type: kubernetes.io/service-account-token
